title: Le Pique Cul
email: contact@piquecul.fr
description: "bulletin sarcastique des cimes qui fait couiner les puissances du monde d'avant"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.piquecul.fr"
locale: fr_FR
facebook_username: PiqueCul
google_analytics_id: G-Q21D6BB48T
locale: fr_FR
twitter:
  username: PiqueCul
  card: summary

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
css:
  color1: "#FF2400"
  color2: "#D11E00"
  body_color: "#f9fafb"
